# Generated by Django 4.2.3 on 2023-07-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_food_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='desc',
        ),
    ]
