# Generated by Django 4.2.3 on 2023-07-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_remove_food_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
